import { test, expect } from '@playwright/test';
test('catalog → register → checkout → private history → login, on desktop and mobile', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const email = `e2e-${Date.now()}@example.test`;
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'iPhone 17' })).toBeVisible();
  await page.screenshot({ path: 'test-results/catalog-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Schimbă limba' }).click();
  await expect(page.getByRole('heading', { name: 'The iMag collection' })).toBeVisible();
  await page.getByRole('button', { name: 'Laptops', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'MacBook Pro M4' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'iPhone 17' })).toHaveCount(0);
  await page.getByRole('button', { name: 'All products' }).click();
  await page.getByLabel('Search products').fill('iPhone');
  await page.getByRole('button', { name: 'Add to bag', exact: true }).click();
  await page.getByRole('link', { name: 'Bag (1)' }).click();
  await page.getByRole('link', { name: 'Sign in to order' }).click();
  await page.getByRole('link', { name: 'Create account', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('iMag Test');
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Strong-e2e-password');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your good choices.' })).toBeVisible();
  await page.getByRole('button', { name: 'Increase quantity' }).click();
  await page.getByRole('button', { name: 'Place order', exact: true }).click();
  await expect(page.getByText('Your order has been recorded successfully.')).toBeVisible();
  await expect(page.getByText('iPhone 17 × 2')).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Strong-e2e-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'My orders', exact: true }).click();
  await expect(page.getByText('iPhone 17 × 2')).toBeVisible();
  await page.getByRole('link', { name: 'Catalog', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Change language' }).click();
  await expect(page.getByRole('heading', { name: 'Colecția iMag' })).toBeVisible();
  await page.screenshot({ path: 'test-results/catalog-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
